name: Deploy pre-release

on:
  release:
    types: [prereleased]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: tag number
        run : echo ${{ github.event.release.tag_name }}

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn

      - name: Run Tests
        env:
          CI: true
        run: yarn test

      - name: Build
        run: yarn build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:

    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Install firebase tools
        run: sudo npm install -g firebase-tools

      # - name: Checkout Repo
      #   uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - name: Set up project
        run: firebase use ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}

      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only hosting --project ${{ secrets.PROJECT_STAGING_ID }}
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to staging site
        run: firebase deploy --only hosting:staging --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }} Tag version ${{ github.event.release.tag_name }}"

      - name: Archive build Artifact
        uses: actions/upload-artifact@master
        with:
          path: build2
